package model

const (
	NAT_PLATFORM    = "NAT"
	ROUTER_PLATFORM = "ROUTER"
	RMQ_PLATFORM    = "RMQ"
	REDIS_PLATFORM  = "REDIS"
	CEPH_PLATFORM   = "CEPH"
	VPE_PLATFORM    = "VPE"
	CMP_PLATFORM    = "CMP"
	DB_PLATFORM     = "DB"
	PRR_PLATFORM    = "PRR"
	TASKER_PLATFORM = "TASKER"
	WORKER_PLATFORM = "WORKER"
	WNP_PLATFORM    = "WNP"
	SYN_PLATFORM    = "SYN"
	ETCD_PLATFORM   = "ETCD"
)
